### PR TITLE
Issue #134 discussion & merge

### PR DESCRIPTION
**Pull request by unquietwiki**
@geoperez @Israel-94 I can't remember the last time I zoned-out like this on code. Webpack 4 is a pain; but I think I got things to where you can do some ngc compile as a build step.  But I know you guys just did some PasswordController thing as well too. There's a references file to help; and the old webpack config, if you think the attempt to upgrade that is a lost cause. Could always try going to "Gulp" too, maybe.

Current concept: **AOT-compile Angular/TS files** -> **JS** -> **Webpack** -> **wwwroot** contents; executed by upgraded C# backend.

### CODE REVIEW

**Comment by unquietwiki** [comment]
If nobody can't fix Webpack in the next few days, I'd be willing to try converting the build setup to Gulp. There's plenty of precedent for it, so it seems.

- https://github.com/paislee/healthy-gulp-angular
- https://hackernoon.com/getting-started-with-gulp-4-for-angular-1280a78fa91a
- https://blog.angular-university.io/what-every-angular-project-likely-needs-and-a-gulp-build-to-provide-it/

**Comment by geoperez** [comment]
@unquietwiki can you merge from `master `and match your `PasswordController.cs`, and `Startup.cs` please?

**Comment by unquietwiki** [comment]
@geoperez @Israel-94 @AnyxLeo I think I have all your recent changes added in, plus set output to TS+Babel to try working with the Angular 5 stuff per #138 . There's still some issue with the output: @Israel-94 , you have any ideas?

**Comment by geoperez** [comment]
You may ignore Codacy, I need to review the lints. 

I hope today clone your branch and review it.

**Comment by Israel-94** [comment]
@unquietwiki I think we can reduce the webpack config, some loaders are not needed it like JSON or CSS, we can just pass the `raw-loader` to HTML and CSS, also we can use another script to build webpack in production mode that makes the files smaller and if you want to use brotli you can use it, but I think we are going to use this webpack config unless something else changes. Also, I am going to check the problem with the new password matching validator. Tell me what you think.

- To run webpack in production mode, add something like this in the script section on the package.json
```json
"build:prod": "./node_modules/.bin/webpack -p"
```

- The webpack configuration
```js
const { CommonsChunkPlugin } = require('webpack').optimize
const { SourceMapDevToolPlugin } = require('webpack');

const CopyWebpackPlugin = require('copy-webpack-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const WebpackCleanupPlugin = require('webpack-cleanup-plugin')

const webpack = require('webpack')
const path = require('path')

module.exports = {
  devtool: 'source-map',
  devServer: {
    historyApiFallback: true
  },
  resolve: {
    extensions: ['.ts', '.js', '.css']
  },
  entry: {
    'main': './ClientApp/main.ts',
    'vendor': './ClientApp/vendor.ts',
    'polyfills': './ClientApp/polyfills.ts'
  },
  output: {
    path: path.join(process.cwd(), './wwwroot'),
    filename: '[name].bundle.js',
    chunkFilename: '[id].chunk.js',
  },
  module: {
    rules: [
        { test: /\.html$/, loader: 'raw-loader' },
        { test: /\.css$/, loader: 'raw-loader' },
      {
        test: /\.ts$/,
        loaders: ['awesome-typescript-loader?useBabel=false', 'angular2-template-loader']
      }
    ]
  },
  plugins: [
    new WebpackCleanupPlugin(),
    new CommonsChunkPlugin({
      name: ['main', 'vendor', 'polyfills']
    }),
    new HtmlWebpackPlugin({
      template: './ClientApp/index.html'
    }),
    new webpack.ContextReplacementPlugin(
      // The (\\|\/) piece accounts for path separators in *nix and Windows
      /angular(\\|\/)core(\\|\/)@angular/,
      './ClientApp', // location of your src
      {} // a map of your routes
    ),
    new webpack.ContextReplacementPlugin(
      // The (\\|\/) piece accounts for path separators in *nix and Windows
      /@angular(\\|\/)core(\\|\/)esm5/,
      './ClientApp', // location of your src
      {} // a map of your routes
      ),
    new SourceMapDevToolPlugin({
        "filename": '[file].map[query]',
        "moduleFilenameTemplate": '[resource-path]',
        "fallbackModuleFilenameTemplate": '[resource-path]?[hash]',
        "sourceRoot": 'webpack:///'
    }),
    new CopyWebpackPlugin([{
      'context': 'ClientApp',
      'to': '',
      'from': {
        'glob': 'manifest.json',
        'dot': true
      }
    }, {
      'context': 'ClientApp',
      'to': '',
      'from': {
        'glob': 'assets/**/*',
        'dot': true
      }
    },
    {
      'context': 'ClientApp',
      'to': '',
      'from': {
        'glob': 'web.config',
        'dot': true
      }
    }
    ], {
      'ignore': [
        '.gitkeep'
      ],
      'debug': 'warning'
    })
  ]
}

```

**Comment by unquietwiki** [comment]
I had added the CSS stuff trying to get rid of any Angular errors in the
compilation. If you're getting to the validator error without that in
there, then I'm fine with this. And I'm also fine with Brotli not being
default: you should keep an eye on that space, because it looks like it'll
be an option for .NET Core 2.1 ASP.NET.

One more thing: can we get "defaultDomain" added back in, while you're
fixing the validator? The config file logic is still in place, but nothing
seems to be using it. Thanks!

**Comment by geoperez** [comment]
Do you need help to merge the C# code?

**Comment by Israel-94** [comment]
@unquietwiki we open a [branch](https://github.com/unosquare/passcore/tree/unquietwiki-master) if you want to check it out

**Comment by unquietwiki** [comment]
@geoperez @Israel-94 Thanks for the branch. I tried to merge in updates from today to it, but get 403 error on committing.

**Comment by geoperez** [comment]
Give me your github email to grant your permissions

**Comment by unquietwiki** [comment]
unquietwiki@gmail.com

**Comment by geoperez** [comment]
Done, maybe we can use the other branch and create a new PR.

**Comment by unquietwiki** [comment]
@geoperez Agreed. Thanks for having me aboard!

**Pull request closed without merging**
