### PR TITLE
Support for Pwned Passwords API

### PR DESCRIPTION
**Pull request by jagbarcelo**
**PassCore Server**
- OS: [Windows | Linux | macOS]
- Provider: [Active Directory | LDAP]

**Describe the intention of the PR** 
Support for Pwned Passwords API

### CODE REVIEW

**Comment by geoperez** [comment]
Something is failing with Ubuntu build.

**Comment by jagbarcelo** [comment]
I'm sorry but I had no continuous integration tests in place for my repository. I forgot to add a reference to the new PwnedPasswordsSearch project in your Unosquare.PassCore.Web project. It compiled and run just fine with Visual Studio, but it seems Ubuntu builds are more strict about missing references. I have uploaded these changes to my repo. Should I do another PR or is there any way to update this one? Again, I'm sorry. I'm new with this.

**Comment by geoperez** [comment]
I was thinking that probably we might need a setting to set this on/off. What do you think?

Also, a brief explanation in the README file, similar to what you put in the issue.

**Comment by jagbarcelo** [comment]
I do not see any reason why someone wouldn't want this for their users. Anyway, I think there should be an easy way to disable it too (in case the service does not work as expected in the future for instance). I didn't do it myself because I do not understand the underlying code so much as you, developers and didn't want to mess anything more than just the necessary.

Regarding your comment about the README... do you mean that I should update the README.md file in my repo explaining this feature and make a PR just for that?

**Comment by geoperez** [comment]
You can update your README file copy in your fork, and this can be included in this PR too.

I can review later the option to toggle this functionality :)

**Comment by geoperez** [comment]
Thanks!

**Pull request merged**
