### PR TITLE
Optional URL param for userName

### PR DESCRIPTION
**Pull request by Jrsnow8921**
In reference to my question #115 - This is how I was able to achieve what I wanted. 

This will enable an optional param to be passed to the URL to fill in the UserName field. 
Ex:
  http://localhost:7000/?userName=testuser@domain.com

### CODE REVIEW

**Comment by geoperez** [comment]
Thank you, let me check the PR.

**Comment by Jrsnow8921** [comment]
@geoperez  you're welcome!

**Comment by geoperez** [comment]
@mariodivece thoughts?

**Comment by geoperez** [comment]
@Jrsnow8921 just one thing, can you explain this feature? Maybe inside "Customization and Configuration" section

**Comment by Jrsnow8921** [comment]
@geoperez  explanation added to the "Customization and Configuration"  section of README.md

**Comment by geoperez** [comment]
Thank you!

**Comment by Jrsnow8921** [comment]
You're welcome! @geoperez

**Pull request merged**
