### PR TITLE
Adding changes to implement pure LDAP provider

### LINKED ISSUE #195: Adding pure LDAP Password Provider -- support Linux hosting
I have implemented a [pure LDAP-based Password Change Provider](https://github.com/ebekker/passcore) using the [Novell LDAP port](https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard) to .NET Standard.

I've successfully deployed and tested it on both Windows and Linux hosts (CentOS7).

I did not want to disturb the existing code base too much so the current integration uses conditional compilation to produce a build of PassCore that is strictly LDAP.

If this is something others are interested in, I can submit a PR to integrate this back upstream but it might be useful to add some sort of multi-provider support (i.e. config-driven provider selection) so as not to produce multiple builds.

### PR DESCRIPTION
**Pull request by ebekker**
Fixes #195

### CODE REVIEW

**Comment by geoperez** [comment]
Travis is failing:

https://travis-ci.org/unosquare/passcore/builds/414566088#L2030

**Comment by ebekker** [comment]
Just committed a change to declare `<LangVer>7.3</LangVer>` that should fix the Travis issue.  Not sure why AV bombed out, no detail there.

**Comment by ebekker** [comment]
Hmm, Travis still failed with the same error -- now I'm confused.  Why would it be failing on [this](https://github.com/unosquare/passcore/blob/a349bd367ada95c86d05e4e160582bb4b08231ac/src/Zyborg.PassCore.PasswordProvider.LDAP/LdapPasswordChangeProvider.cs#L42)?

**Comment by geoperez** [comment]
Let me check on my computer.

**Comment by ebekker** [comment]
Doh! I'm an idiot, the error is valid, I committed before looking at the build result on my local computer.

**Comment by geoperez** [comment]
Thanks. We are going to test and publish a new release soon.

**Pull request merged**
