### PR TITLE
.NET Core 2.0 and Angular 6

### PR DESCRIPTION
**Pull request by geoperez**

### CODE REVIEW

**Comment by unquietwiki** [comment]
@geoperez @Israel-94 you guys were on the ball today with helping me get our code entries in sync. Muchas gracias.

(ponders) Only holdback now appears to be the matching validator. As you can see from today's commits, I junked the previous AOT/Webpack4 attempt; since Israel's attempt to clean things up made that look rather dumpy. http://www.codiodes.com/match-password-validation/ came up on Google: might be useful.

**Comment by geoperez** [comment]
@unquietwiki do you have your editor to start a code block curly brace on the same line?

`if (true) {
// do something
}`

instead of 

`if (true) 
{
// do something
}`

I found some files are the same, only with this format change. We use the curly brace in a new line in all project, like most of the C# open source projects.

**Comment by unquietwiki** [comment]
Yeah the code format was based on autofornatting from OmniSharp via a VS
Code plugin. And I added the makefile as a quick way to clean up the node
dependencies; it's not used in the actual build process.

**Comment by geoperez** [comment]
Can you match the code format like Visual Studio?

**Comment by unquietwiki** [comment]
I'd have to double check to make sure I don't have some odd OmniSharp.json
sitting somewhere I'm not seeing. AFAIK both use OmniSharp Rosyln for C#
support.

**Comment by Israel-94** [comment]
@unquietwiki I updated the `passwordMatch` validator to use with reactive forms, now the api/password is not returning the labels and the information for the client application

**Comment by unquietwiki** [comment]
@Israel-94 I'll take a look. Thanks for fixing the validator.

@geoperez I found some resources regarding how to show you all what extensions I've been using; as well as trying to figure out how to enforce your desired style with them.

**Comment by unquietwiki** [comment]
@Israel-94 I went over the docs best I can, as well as a migration tool I had checked before. It looks like the "this" errors go away if you separate stuff from the old constructor into OnInit & OnChange; however, you & @geoperez are going to know better as to what does what. Please check **app.change-password.ts** when you guys are able. Thanks!

**Comment by unquietwiki** [comment]
@Israel-94 @geoperez Sorry for the delay today: had to reload my work machine. I fixed the favicon bundling, and tweaked the checking on the username validation. Testing for an email address defeats the purpose of having "defaultDomain"; there is probably a way to have it to a check for that, if the defaultDomain is null / empty; but is it required for our needs?

I'm actually having trouble verifying that my tweaks actually work: sometimes password resets don't work right here, and it's something that's mystified me and my boss (probably some weird GPO issue). I'll let you know if it end up does working for someone, else please let me know if we're all good on this.  👍

**Comment by geoperez** [comment]
But did you remove the email validator in all cases?

**Comment by unquietwiki** [comment]
Yeah. I set it to text, not email.

**Comment by Israel-94** [comment]
@unquietwiki Can you explain a little more why removed the email validator

**Comment by unquietwiki** [comment]
If using a defaultDomain, then you only need to specify the username for a
reset. Email validator explicitly requires user@domain format. My users
were getting confused about using their company email address, hence the
modifications.

**Comment by geoperez** [comment]
Yeah, but we need to support both cases. Adjusting the input with the server settings will be required.

**Comment by unquietwiki** [comment]
I figure a custom validator on the backend. Frontend will still be limited
to string or email.

On Apr 30, 2018 7:39 AM, "Geovanni Perez" <notifications@github.com> wrote:

Yeah, but we need to support both cases. Adjusting the input with the
server settings will be required.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/unosquare/passcore/pull/139#issuecomment-385418570>,
or mute
the thread

**Comment by geoperez** [comment]
I don't know if there is need to validate an email in backend. @Israel-94 can you check how to handle this?

**Comment by geoperez** [comment]
ASP.NET Core already has the DI integration. It's a cool new feature in WebForms, but we are not using .NET Framework in this branch and neither WebForms.

**Comment by Israel-94** [comment]
@geoperez @unquietwiki  I am going to handle the defaultDomain as a custom configuration on the  `appsettings `, so that the client will have two scenarios one when defaultDomain is configured it and the default

**Comment by unquietwiki** [comment]
@Israel-94 I was able to successfully compile your latest commit, and have it live on my end. I'll advise if there are any problems; otherwise, from looking at the changes, you appear to have threaded the needle. 🥇

**Comment by Israel-94** [comment]
@unquietwiki I ran the application with the new changes and It is working for me, maybe it has something to do with the cache of the old files in the browser, try disable the cache in the browser and reload the page.

**Comment by unquietwiki** [comment]
@Israel-94 I had tried in a different browser when I ran into the issue, but it's possible something in the cache is conflicting with the newer page. I saw @geoperez just pushed some WinAPI changes: I'll hold off on another test until he's done.

**Comment by geoperez** [comment]
We are done, you can try it?

**Comment by geoperez** [comment]
@Israel-94 can you take a look?

**Comment by Israel-94** [comment]
@unquietwiki I made what I think are the last changes, Can you test to know if it works and then do the merge?

**Comment by unquietwiki** [comment]
I can pull the changes in a bit. Not at the office today, but I can remote
in & get that setup for use. Thanks!

**Comment by unquietwiki** [comment]
@Israel-94 @geoperez I have the new build live, and reached out to some folks. The DirectoryServices NuGet package received an RC1 update, so I told it to use that. I'll report back what the results are. Thanks! 👍

**Comment by unquietwiki** [comment]
@Israel-94 @geoperez Still getting 400 errors on reset attempts. Even made sure I had the latest appsettings.json file change. 🤕 

Looking back at all of this, I don't think this has properly worked for the actual reset part since commit ab0fcd9 . Is there something I can do to further get better debugging on this? Anything about your test environment / AD setups that would indicate why it'd work for you; and not for my folks?

**Comment by Israel-94** [comment]
@unquietwiki We have the latest changes and everything its fine on our side, Could you check what errors do you have or copy/paste the 400 errors to see whats happening?

**Comment by unquietwiki** [comment]
@geoperez @Israel-94 I've spun up the latest build, and will report back. Report from one of the other IT guys suggested that he thought folks weren't abiding to our password complexity requirement; I'm not sure from the new logic you guys added as to how that gets expressed.

**Comment by unquietwiki** [comment]
@Israel-94 I saw you just made some changes, and they look important. Please advise when you want me to rebuild. Thanks!

**Comment by unquietwiki** [comment]
@geoperez @Israel-94 Yeah, I can see why it's annoying. In looking at the few remaining errors, I found that some of the defaultDomain stuff could use tightening. I'm testing some changes on my end momentarily.

**Comment by unquietwiki** [comment]
@geoperez @Israel-94 Even with the latest attempt at fixes, and more clear error messages; still getting "invalid username or password" error. :(

**Comment by geoperez** [comment]
Are you testing with default domain? Our side is not using it.

**Comment by unquietwiki** [comment]
I am, yes

**Comment by Israel-94** [comment]
@unquietwiki We made some changes and test with default domain, everything works fine, Can you pull the latest and tell us your results? after this, we plan to do the merge.

**Comment by geoperez** [comment]
Let's merge!!!!!!!!!!

**Comment by unquietwiki** [comment]
@geoperez Should we delete the old branch now?

**Pull request merged**
