### PR TITLE
Further improvements to support .NET 6 migration

### PR DESCRIPTION
**Pull request by unquietwiki**
Hey @geoperez and crew. I had to re-install this for one of my employers, and used the opportunity to see if there was anything I was running into. I have yesterday's changes running fine; today's stuff is the start of some refactoring, which you might want to review before doing any more. Part of that may help with an issue I've run into, where a failed new password (because of requirements on SAMBA/AD), comes up as an incorrect current password error. I also ended up running this without Docker again; if there was an easier way to separate out & map the JSON config for that, I think it'd definitely help that use.

Hope you all are keeping safe & well.

### CODE REVIEW

**Comment by unquietwiki** [comment]
@geoperez Also, I dunno if you can update your AppVeyor config, but it's failing on .NET 6 builds; seems like it's using VS 2017 stuff.

**Comment by geoperez** [comment]
Hi @unquietwiki , quick question. Why do you change from "var" to type in variable declarations?

I'll check the Appveyor thing.

**Comment by unquietwiki** [comment]
> Hi @unquietwiki , quick question. Why do you change from "var" to type in variable declarations?
> 
> I'll check the Appveyor thing.

Yeah, I was hesitant on the var-change; but VS kept suggesting it, and it was coming up with suggestions that exposed the nullable types, so that seemed more intuitive. A lot of the stuff SonarLint flagged relates to either nulls, or reference issues.

**Comment by geoperez** [comment]
AppVeyor settings have been updated.

**Comment by unquietwiki** [comment]
@geoperez Managed to catch me up early; cat woke me up. I re-added react as a direct-dependency, even though the Uno stuff loads it. Can run build on my machine just fine; not sure why it's failing in Appveyor. Both my machine & my other install are using Node 16.x, if that helps.

**Comment by geoperez** [comment]
Let me try to test it on my local env.

**Comment by VM-Master** [comment]
Hi,
any updates regarding .NET Core Version? We wanna get rid of old unsupported .NET Core Version.

**Pull request closed without merging**
